# Generated by Django 4.1.4 on 2023-01-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulatracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulalog',
            old_name='formula_consumed',
            new_name='feed_amount',
        ),
    ]
