# Generated by Django 4.1.4 on 2023-01-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulatracker', '0003_alter_formulalog_formula_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulalog',
            name='time_of_feed',
            field=models.TimeField(null=True),
        ),
    ]
