# Generated by Django 4.1.4 on 2023-01-24 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulatracker', '0004_formulalog_time_of_feed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulalog',
            name='formula_type',
        ),
        migrations.DeleteModel(
            name='Formula',
        ),
    ]
