# Generated by Django 4.1.4 on 2023-01-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulatracker', '0005_remove_formulalog_formula_type_delete_formula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulalog',
            name='feed_amount',
            field=models.SmallIntegerField(null=True),
        ),
    ]
