# Generated by Django 4.1.4 on 2023-02-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulatracker', '0013_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='feed_goal',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
