# Generated by Django 4.1.4 on 2023-02-05 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulatracker', '0015_rename_date_of_feed_formulalog_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulalog',
            name='feed_amount',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
