# Generated by Django 4.1.4 on 2023-02-06 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulatracker', '0017_units'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Units',
        ),
    ]
