# Generated by Django 4.1.4 on 2023-02-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulatracker', '0019_user_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='units',
            field=models.CharField(choices=[('IMPERIAL', 'Imperial'), ('METRIC', 'Metric')], default='Imperial', max_length=8),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
