# Generated by Django 4.1.4 on 2023-02-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulatracker', '0021_alter_user_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='units',
            field=models.CharField(choices=[('floz', 'fluid ounces'), ('mL', 'milliliters')], default='fluid ounces', max_length=8),
        ),
    ]
