# Generated by Django 4.1.4 on 2023-02-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulatracker', '0022_alter_user_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='weight_units',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lbs', 'Pounds')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='units',
            field=models.CharField(choices=[('oz', 'Us ounces'), ('mL', 'milliliters')], default='fluid ounces', max_length=8),
        ),
    ]
