# Generated by Django 4.1.4 on 2023-02-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulatracker', '0023_weight_weight_units_alter_user_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='child_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='units',
            field=models.CharField(choices=[('IMPERIAL', 'Imperial'), ('METRIC', 'Metric')], default='Metric', max_length=8),
        ),
    ]
