# Generated by Django 4.1.4 on 2023-02-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulatracker', '0024_user_child_name_alter_user_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='child_name',
            field=models.CharField(default='Child', max_length=50, null=True),
        ),
    ]
