# Generated by Django 4.1.4 on 2023-02-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulatracker', '0025_alter_user_child_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='units',
            field=models.CharField(choices=[('METRIC', 'Metric'), ('IMPERIAL', 'Imperial')], default='Metric', max_length=8),
        ),
    ]
