# Generated by Django 4.1.4 on 2023-02-10 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulatracker', '0026_alter_user_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weight',
            name='weight_units',
        ),
    ]
