# Generated by Django 4.1.4 on 2023-02-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulatracker', '0029_remove_formulalog_dayfilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
    ]
