# Generated by Django 4.1.4 on 2023-02-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulatracker', '0030_alter_weight_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
