# Generated by Django 4.1.4 on 2023-02-15 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulatracker', '0031_alter_weight_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
